name: my_flutter_app
description: "Application Flutter professionnelle avec architecture propre pour gestion de sinistres"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  flutter_secure_storage: ^9.2.2
  
  # State Management - Versions stables
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.2.0
  
  # Utils - Versions stables
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  
  # Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.1
  
  # Location
  geolocator: ^10.1.0
  
  # Image Picker
  image_picker: ^1.0.7
  
  # UI - Versions stables
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # UI Enhancements
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Navigation et UI supplémentaires
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  package_info_plus: ^8.3.0
  device_info_plus: ^9.1.2
  
  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  
  # Testing
  coverage: ^1.6.3
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/ 