name: my_flutter_app
description: "Application Flutter professionnelle avec architecture propre pour gestion de sinistres"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  flutter_secure_storage: ^9.2.2
  firebase_app_check: 0.3.2+7
  
  # Supabase
  supabase_flutter: ^2.9.1
  
  # State Management - Versions stables
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^15.2.0
  
  # Utils - Versions stables
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logger: ^2.0.2
  
  # Storage
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  
  # Location
  geolocator: ^14.0.1
  
  # Image Picker
  image_picker: ^1.0.7
  
  # UI - Versions stables
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  
  # Maps
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  
  # UI Enhancements
  lottie: ^3.3.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  
  # Navigation et UI supplémentaires
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.0
  package_info_plus: ^8.0.0
  device_info_plus: ^11.0.0
  
  # Testing
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  
  # Notifications
  flutter_local_notifications: ^19.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.6
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  
  # Testing
  coverage: ^1.6.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
